name: Build Piper for Unity Android

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    # Shared environment for every step in the job
    env:
      ANDROID_ABI: arm64-v8a
      ANDROID_PLATFORM: android-21
      ORT_VERSION: 1.17.0        # <-- first version with android-aarch64 .tgz

    steps:
    # -------------------------------------------------
    # 0. Source checkout and host tooling
    # -------------------------------------------------
    - name: Checkout Piper
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build autoconf automake libtool pkg-config cmake curl

    - name: Set up Android NDK
      id: ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d

    # -------------------------------------------------
    # 1. Build eSpeak-NG for Android (arm64)
    # -------------------------------------------------
    - name: Clone eSpeak-NG
      run: git clone https://github.com/espeak-ng/espeak-ng.git

    - name: Build eSpeak-NG
      run: |
        export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
        cd espeak-ng
        mkdir -p build-android && cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ANDROID_ABI \
          -DANDROID_PLATFORM=$ANDROID_PLATFORM \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=install \
          -G Ninja
        ninja
        ninja install            # puts headers & libs under install/
        ls -lh install/lib || true

    # -------------------------------------------------
    # 2. Build piper-phonemize for Android
    # -------------------------------------------------
    - name: Clone piper-phonemize
      run: git clone https://github.com/rhasspy/piper-phonemize.git

    - name: Build piper-phonemize
      run: |
        export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
        cd piper-phonemize
        mkdir -p build-android && cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ANDROID_ABI \
          -DANDROID_PLATFORM=$ANDROID_PLATFORM \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DESPEAK_NG_DIR=../../espeak-ng/build-android/install \
          -DONNXRUNTIME_VERSION=$ORT_VERSION \
          -G Ninja
        ninja
        ls -lh libpiper_phonemize.so || true

    # -------------------------------------------------
    # 3. Build Piper itself for Android
    # -------------------------------------------------
    - name: Build Piper
      run: |
        export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
        mkdir -p build-android && cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ANDROID_ABI \
          -DANDROID_PLATFORM=$ANDROID_PLATFORM \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -Dphonemize_DIR=../piper-phonemize/build-android \
          -DESPEAK_NG_DIR=../espeak-ng/build-android/install \
          -G Ninja
        ninja
        ls -lh libpiper.so || true

    # -------------------------------------------------
    # 4. Publish the three .so files as artifacts
    # -------------------------------------------------
    - name: Upload Piper .so
      uses: actions/upload-artifact@v4
      with:
        name: libpiper-android
        path: build-android/libpiper.so

    - name: Upload piper-phonemize .so
      uses: actions/upload-artifact@v4
      with:
        name: libpiper_phonemize-android
        path: piper-phonemize/build-android/libpiper_phonemize.so

    - name: Upload eSpeak-NG .so
      uses: actions/upload-artifact@v4
      with:
        name: libespeak-ng-android
        path: espeak-ng/build-android/install/lib/libespeak-ng.so
