name: Build Piper for Unity Android

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Piper
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build autoconf automake libtool pkg-config cmake curl unzip

      - name: Set up Android NDK
        id: ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Clone eSpeak-NG
        run: |
          git clone https://github.com/espeak-ng/espeak-ng.git

      - name: Build eSpeak-NG for Android (arm64)
        run: |
          export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
          cd espeak-ng
          mkdir build-android && cd build-android
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS_RELEASE="-s -fvisibility=hidden" \
            -DCMAKE_CXX_FLAGS_RELEASE="-s -fvisibility=hidden" \
            -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--no-undefined" \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -G Ninja
          ninja
          # Install into a staging area
          DESTDIR=$(pwd)/install-android ninja install
          # eSpeak-NG's CMake install sometimes omits subfolders—manually bring in the headers
          mkdir -p install-android/usr/local/include
          cp -r ../src/include/* install-android/usr/local/include/
          ls -R install-android/usr/local | head -n20

      - name: Download ONNX Runtime for Android (arm64)
        run: |
          ORT_VERSION=1.16.3
          mkdir -p third_party && cd third_party

          # Try several possible asset names until one works
          ASSETS=(
            "onnxruntime-android-aarch64-${ORT_VERSION}.tgz"
            "onnxruntime-android-aarch64-${ORT_VERSION}.zip"
            "onnxruntime-android-arm64-v8a-${ORT_VERSION}.tgz"
            "onnxruntime-android-arm64-v8a-${ORT_VERSION}.zip"
          )
          for asset in "${ASSETS[@]}"; do
            URL="https://github.com/microsoft/onnxruntime/releases/download/v${ORT_VERSION}/${asset}"
            echo "Trying $URL"
            if curl -L --fail -o asset "$URL"; then
              echo "Downloaded $asset"
              if [[ "$asset" == *.tgz ]]; then tar -xzf asset
              else unzip -q asset; fi
              break
            else
              echo "Failed to download $asset"
            fi
          done

          EXTRACTED=$(find . -maxdepth 1 -type d -name "onnxruntime-android*" | head -n1)
          mv "$EXTRACTED" onnxruntime-android

          echo "ORT_ANDROID_DIR=$(pwd)/onnxruntime-android" >> "$GITHUB_ENV"
          ls -R onnxruntime-android | head -n20

      - name: Clone piper-phonemize
        run: |
          git clone https://github.com/rhasspy/piper-phonemize.git

      - name: Build piper-phonemize for Android
        run: |
          export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
          cd piper-phonemize
          mkdir build-android && cd build-android
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DESPEAK_NG_LIBRARY=${{ github.workspace }}/espeak-ng/build-android/install-android/usr/local/lib/libespeak-ng.so \
            -DESPEAK_NG_INCLUDE_DIR=${{ github.workspace }}/espeak-ng/build-android/install-android/usr/local/include \
            -Donnxruntime_DIR=$ORT_ANDROID_DIR \
            -DCMAKE_C_FLAGS_RELEASE="-s -fvisibility=hidden" \
            -DCMAKE_CXX_FLAGS_RELEASE="-s -fvisibility=hidden" \
            -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--no-undefined" \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -G Ninja
          ninja
          ls -lh libpiper_phonemize.so

      - name: Build Piper for Android
        run: |
          export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
          mkdir build-android && cd build-android
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -Dphonemize_DIR=${{ github.workspace }}/piper-phonemize/build-android \
            -Donnxruntime_DIR=$ORT_ANDROID_DIR \
            -DCMAKE_C_FLAGS_RELEASE="-s -fvisibility=hidden" \
            -DCMAKE_CXX_FLAGS_RELEASE="-s -fvisibility=hidden" \
            -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--no-undefined" \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -G Ninja
          ninja
          ls -lh libpiper.so

      - name: Upload Piper Android .so
        uses: actions/upload-artifact@v4
        with:
          name: piper-android-so
          path: build-android/libpiper.so

      - name: Upload piper-phonemize Android .so
        uses: actions/upload-artifact@v4
        with:
          name: piper-phonemize-android-so
          path: piper-phonemize/build-android/libpiper_phonemize.so

      - name: Upload eSpeak-NG Android .so
        uses: actions/upload-artifact@v4
        with:
          name: espeak-ng-android-so
          path: espeak-ng/build-android/install-android/usr/local/lib/libespeak-ng.so
