name: Build Piper for Unity Android

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    # ------------------------------------------------------------------ #
    # 1 · Checkout                                                       #
    # ------------------------------------------------------------------ #
    - name: Checkout source
      uses: actions/checkout@v4

    # ------------------------------------------------------------------ #
    # 2 · Host-side tools                                                #
    # ------------------------------------------------------------------ #
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build autoconf automake libtool \
                               pkg-config cmake curl unzip

    # ------------------------------------------------------------------ #
    # 3 · Android NDK                                                   #
    # ------------------------------------------------------------------ #
    - name: Set up Android NDK
      id: ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d

    # ------------------------------------------------------------------ #
    # 4 · eSpeak-NG (arm64-v8a)                                          #
    # ------------------------------------------------------------------ #
    - name: Clone eSpeak-NG
      run: git clone https://github.com/espeak-ng/espeak-ng.git

    - name: Build eSpeak-NG (arm64-v8a)
      run: |
        export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
        cd espeak-ng
        mkdir build-android && cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -G Ninja
        ninja
        cmake --install . --prefix install-android
        echo "ESPEAK_NG_ANDROID=$GITHUB_WORKSPACE/espeak-ng/build-android/install-android" >> $GITHUB_ENV

    # ------------------------------------------------------------------ #
    # 5 · ONNX Runtime (Android AAR → headers + lib)                     #
    # ------------------------------------------------------------------ #
    - name: Download ONNX Runtime (Android arm64)
      run: |
        ORT_VERSION=1.17.0
        mkdir -p third_party && cd third_party
        curl -L -o ort.aar \
          "https://repo1.maven.org/maven2/com/microsoft/onnxruntime/onnxruntime-android/${ORT_VERSION}/onnxruntime-android-${ORT_VERSION}.aar"
        unzip -q ort.aar -d ort
        mkdir -p onnxruntime-android/include onnxruntime-android/lib
        cp -r ort/headers/*  onnxruntime-android/include/
        cp    ort/jni/arm64-v8a/libonnxruntime.so onnxruntime-android/lib/
        echo "ORT_ANDROID_DIR=$(pwd)/onnxruntime-android" >> $GITHUB_ENV

    # ------------------------------------------------------------------ #
    # 6 · piper-phonemize (arm64-v8a) – INSTALLED                       #
    # ------------------------------------------------------------------ #
    - name: Clone piper-phonemize
      run: git clone https://github.com/rhasspy/piper-phonemize.git

    - name: Build piper-phonemize (arm64-v8a)
      run: |
        export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
        cd piper-phonemize
        mkdir build-android && cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DESPEAK_NG_DIR=$ESPEAK_NG_ANDROID \
          -DONNXRUNTIME_DIR=$ORT_ANDROID_DIR \
          -DTHREADS_PREFER_PTHREAD_FLAG=ON \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_INSTALL_PREFIX=install-android \
          -G Ninja
        ninja
        cmake --install . --prefix install-android
        echo "PIPER_PHONEMIZE_ANDROID=$(pwd)/install-android" >> $GITHUB_ENV

    # ------------------------------------------------------------------ #
    # 7 · Trim the VERSION file (fixes _PIPER_VERSION newline bug)       #
    # ------------------------------------------------------------------ #
    - name: Strip newline from VERSION
      run: |
        tr -d '\n' < VERSION > VERSION.fix && mv VERSION.fix VERSION

    # ------------------------------------------------------------------ #
    # 8 · Piper core (arm64-v8a)                                         #
    # ------------------------------------------------------------------ #
    - name: Build Piper core (arm64-v8a)
      run: |
        export ANDROID_NDK_HOME=${{ steps.ndk.outputs.ndk-path }}
        mkdir build-android && cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DPIPER_PHONEMIZE_DIR=$PIPER_PHONEMIZE_ANDROID \
          -DESPEAK_NG_DIR=$ESPEAK_NG_ANDROID \
          -DONNXRUNTIME_DIR=$ORT_ANDROID_DIR \
          -DTHREADS_PREFER_PTHREAD_FLAG=ON \
          -DCMAKE_PREFIX_PATH="$PIPER_PHONEMIZE_ANDROID;$ESPEAK_NG_ANDROID;$ORT_ANDROID_DIR" \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -G Ninja
        ninja
        cmake --install . --prefix install-android

    # ------------------------------------------------------------------ #
    # 9 · Ship the three .so files                                       #
    # ------------------------------------------------------------------ #
    - name: Upload Android libraries
      uses: actions/upload-artifact@v4
      with:
        name: piper-android-libs
        path: |
          build-android/install-android/lib/libpiper.so
          piper-phonemize/build-android/install-android/lib/libpiper_phonemize.so
          espeak-ng/build-android/install-android/lib/libespeak-ng.so
