name: Build Piper for Unity

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      phonemize_path: ${{ steps.phonemize.outputs.path }}
    steps:
      - uses: actions/checkout@v4
      - name: Clone piper-phonemize
        run: |
          git clone https://github.com/rhasspy/piper-phonemize.git
          cd piper-phonemize
          mkdir build && cd build
          cmake ..
          cmake --build .
          echo "::set-output name=path::$(pwd)"
        id: phonemize

  build-windows:
    needs: setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy phonemize artifacts
        run: xcopy /s "%{ needs.setup.outputs.phonemize_path }\\Release" build\\phonemize
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Build DLL
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON -Dphonemize_DIR="%cd%/phonemize" -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release
          dir Release
      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: piper-windows-dll
          path: build\\Release\\*.dll

  build-android:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja & NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
      - uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r26d
      - name: Build SO
        run: |
          git clone https://github.com/rhasspy/piper-phonemize.git phon
          mkdir phon/build && cd phon/build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ steps.ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
               -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -G Ninja
          ninja
          cd ../../
          mkdir -p unity_plugin/Android/arm64-v8a
          cp phon/build/libpiper_phonemize.so unity_plugin/Android/arm64-v8a/
          mkdir build_android && cd build_android
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ steps.ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
               -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DBUILD_SHARED_LIBS=ON \
               -Dphonemize_DIR=../phon/build
          ninja
          ls -lh .
      - name: Upload SO
        uses: actions/upload-artifact@v4
        with:
          name: piper-android-so
          path: unity_plugin/Android/arm64-v8a/*.so
