name: Build Piper for Unity

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-windows:
    name: Build Windows DLL
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure and Build (DLL)
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=ON
          cmake --build . --config Release

      - name: Copy DLL
        run: |
          mkdir -p unity_plugin/Windows
          # Replace libpiper.dll with the correct output if different!
          copy build\Release\piper.dll unity_plugin\Windows\piper.dll

      - name: Upload Windows DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: piper-windows-dll
          path: unity_plugin/Windows/piper.dll

  build-android:
    name: Build Android SO
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure and Build (SO)
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          mkdir build_android
          cd build_android
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DBUILD_SHARED_LIBS=ON
          cmake --build . --config Release

      - name: Copy SO
        run: |
          mkdir -p unity_plugin/Android/arm64-v8a
          # Replace libpiper.so with the correct output if different!
          cp build_android/libpiper.so unity_plugin/Android/arm64-v8a/libpiper.so

      - name: Upload Android SO artifact
        uses: actions/upload-artifact@v4
        with:
          name: piper-android-so
          path: unity_plugin/Android/arm64-v8a/libpiper.so
